version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: test_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-network

  frontend:
    build: ./frontend

    depends_on:
      mysql:
        condition: service_healthy
    
    ports:
      - "5173:5173"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
