FROM golang:1.22.2

# Establece el directorio de trabajo
WORKDIR /backend

# Copia los archivos go.mod y go.sum
COPY go.mod go.sum ./

#RUN echo "Acquire::http::Timeout \"20000000\";" > /etc/apt/apt.conf.d/99timeout
# Descarga las dependencias
RUN go mod download

# Copia el resto de los archivos del proyecto
COPY . .

# Compila el proyecto
RUN CGO_ENABLED=0 go build -o main .

# Expone el puerto 8080
EXPOSE 8080

# Define el comando de inicio
CMD ["./main"]